# Generated by Django 4.0.2 on 2022-06-02 12:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('MyAppQuasar42', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MBLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_du_lieu_choisie', models.CharField(choices=[('TR1', 'Terrain1'), ('TR2', 'Terrain2'), ('TR3', 'Terrain3'), ('BSK1', 'Basket1'), ('BSK2', 'Basket2'), ('BSK3', 'Basket3'), ('BX1', 'Boxe1'), ('BX2', 'Boxe2'), ('BX3', 'Boxe3')], default='Terrain1', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MBReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=40)),
                ('Date_choisie', models.DateField()),
                ('Heure_choisie', models.TimeField()),
                ('ref', models.CharField(max_length=6)),
                ('Nom_du_lieu_choisie', models.ForeignKey(default='Terrain1', on_delete=django.db.models.deletion.CASCADE, to='MyAppQuasar42.mblieux')),
            ],
        ),
        migrations.CreateModel(
            name='MBUserForm',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
