# Generated by Django 4.0.2 on 2022-03-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppQuasar42', '0002_contact_delete_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='field_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
