# Generated by Django 4.0.2 on 2022-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppQuasar42', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField(default=0)),
                ('Email', models.EmailField(max_length=40)),
                ('Date_Check_In', models.DateField()),
                ('Date_Check_Out', models.DateField()),
                ('Choix_terrain', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
