# Generated by Django 4.0.2 on 2022-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppQuasar42', '0005_reservation_alter_contact_phone_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Choix_terrain',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Date_Check_In',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='Date_Check_Out',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Date_choisie',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='Heure_choisie',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
