# Generated by Django 4.0.2 on 2022-03-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppQuasar42', '0006_remove_reservation_choix_terrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Nom_du_lieu_choisie',
            field=models.TextField(blank=True),
        ),
    ]
