# Generated by Django 4.0.2 on 2022-04-01 10:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('MyAppQuasar42', '0007_reservation_nom_du_lieu_choisie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=40)),
                ('Nom_du_lieu_choisie', models.TextField(blank=True)),
                ('Date_choisie', models.TimeField(null=True)),
                ('Heure_choisie', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MBUserForm',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameModel(
            old_name='Contact',
            new_name='MBContact',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
