# Generated by Django 4.0.2 on 2022-04-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAppQuasar42', '0008_mbreservation_mbuserform_rename_contact_mbcontact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mbreservation',
            name='ref',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mbreservation',
            name='Date_choisie',
            field=models.DateField(null=True),
        ),
    ]
